---

- hosts: '*'
  vars:
    user: solidfire
  gather_facts: false
  become: true

- import_playbook: gluster-01-show-topo.yml
- import_playbook: gluster-02-heketi-pre.yml
- import_playbook: gluster-03-heketi.yml
- import_playbook: gluster-04-storage-class.yml

