---
# Ansible for OpenEBS
# Requires disk to already be formatted and mounted

- hosts: 'kube-master,kube-node'
  vars:
    trident_installer: https://github.com/NetApp/trident/releases/download/v18.07.0/trident-installer-18.07.0.tar.gz
    namespace: trident
    deploy:    trident
  remote_user: solidfire
  become: true

  tasks:

  - name: Update apt cache
    apt: 
      update_cache: yes
    register: out

  - debug: var=out

  - name: Install apt package nfs-commoon
    package: 
      name:   nfs-common
      state:    present
    register: out

  - debug: var=out

  - name: Start service rpc-statd
    systemd: 
      name:     rpc-statd
      enabled:  yes
      state:    started
    register: out

  - debug: var=out

