---
# Ansible for installing GlusterFS requirements on K8s cluster machines.

- hosts: 'kube-master'
  vars:
      dir_target: '{{ ansible_env.HOME }}'
      namespace: 'heptio-ark'
      deploy: 'ark'
      metallb_config_yaml: 'ark-minio-nodeport.yaml'
  remote_user: solidfire
  become: true
  run_once: true
  environment:

  tasks:

  #- name: Role Facts
  #  set_fact:
  #    block_device: '/dev/sdb'

  - name: Check for Heptio Ark deployment
    shell: "kubectl get deployment {{ deploy }} -n {{ namespace }} --no-headers=1"
    register: check_ark
    ignore_errors: true

  #- name: Change service to type nodeport
  #  command: "helm install {{ chart }} -n {{ helm_name }} --namespace {{ namespace }}"
  #  when: check_metallb.rc != 0
  #  register: out
  #
  #- debug: var=out.stdout
