---
# Ansible for deploying Docker registry

- hosts: 'kube-master'
  vars:
      dir_target: '{{ ansible_env.HOME }}'
      namespace: 'registry'
      helm_name: 'docker-registry'
      chart: 'stable/docker-registry'
      size: '36Gi'
      service_type: 'NodePort'
      deploy: 'docker-registry'
  remote_user: solidfire
  become: true
  run_once: true
  environment:

  tasks:

  #- name: Role Facts
  #  set_fact:
  #    block_device: '/dev/sdb'

  - name: Check for docker-registry deployment
    shell: "kubectl get deployment {{ deploy }} -n {{ namespace }} --no-headers=1"
    register: check_docker_registry
    ignore_errors: true

  - name: Install docker-registry helm chart
    command: "helm install --namespace {{ namespace }} {{ helm_name }} {{ chart }} --set persistence.enabled=true --set persistence.size={{ size }} --set service.type={{ service_type }}"
    when: check_docker_registry.rc != 0
    register: install_chart

  - debug: var=install_chart.stdout_lines

  - name: Check for docker-registry deployment
    shell: "kubectl get deployment {{ deploy }} -n {{ namespace }} --no-headers=1"
    register: check_docker_registry_deploy
    retries: 36
    delay: 1
    until: check_docker_registry_deploy.rc == 0
