---
# Ansible for installing Hashicorp Vault

- hosts: 'kube-master'
  vars:
      #key: 'value'
      dir_target:            '{{ ansible_env.HOME }}/vault'
      vault_github_version:    'v0.1.2'
      vault_namespace:         'vault'
  remote_user: solidfire
  become: true
  run_once: true
  environment:

  tasks:

  - name: Clone Hashicorp Vault repository
    git:
      repo: 'https://github.com/hashicorp/vault-helm.git'
      dest: "{{ dir_target }}"
      version: "{{ vault_github_version }}"
      force: yes



