---
# Ansible for deploying ingress-nginx
# https://kubernetes.github.io/ingress-nginx/deploy/

#- hosts: 'kube-master'
- hosts: '127.0.0.1'
  vars:
      dir_target: '{{ ansible_env.HOME }}'
      namespace: 'ingress-nginx'
      helm_name: 'ingress-nginx'
      helm_repo: 'https://kubernetes.github.io/ingress-nginx'
      chart: 'ingress-nginx/ingress-nginx'
      deploy: 'ingress-nginx-controller'
  remote_user: solidfire
  #become: true
  run_once: true
  environment:

  tasks:

  #- name: Role Facts
  #  set_fact:
  #    block_device: '/dev/sdb'

  - name: Check for ingress nginx deployment
    shell: "kubectl get deployment {{ deploy }} -n {{ namespace }} --no-headers=1"
    register: check_ingress_nginx
    ignore_errors: true

  - name: Add helm repo for ingress nginx
    shell: "helm repo add {{ helm_name }} {{ helm_repo }} && helm repo update"
    when: check_ingress_nginx.rc != 0

  - name: Install ingress nginx helm chart
    command: "helm install {{ helm_name }} {{ chart }} --namespace {{ namespace }} --create-namespace"
    when: check_ingress_nginx.rc != 0
    register: install_chart

  - debug: var=install_chart.stdout_lines

  - name: Check for ingress nginx deployment
    shell: "kubectl get deployment {{ deploy }} -n {{ namespace }} --no-headers=1"
    register: check_ingress_nginx_controller
    retries: 36
    delay: 1
    until: check_ingress_nginx_controller.rc == 0
