---

- hosts: '*'
  vars:
    user: solidfire
  gather_facts: false
  become: true

- import_playbook: openebs-01-pre.yml block_device_openebs="{{ block_device_openebs }}"
- import_playbook: openebs-02-install.yml block_device_openebs="{{ block_device_openebs }}"
