---
# Create container storage volume for OpenEBS
# The raw block device will be formatted and mounted

- hosts: 'openebs'
  vars:
    block_device_openebs: /dev/sde
    mount_point:  /mnt/openebs_disk
    fs_type:      ext4
  #remote_user: solidfire
  become: true

  tasks:

#  - name: Create directory for OpenEBS
#    file:
#      path: "{{ mount_point }}"
#      state: directory
#      mode: 0755
#  
#  - name: Create ext4 Filesystem
#    filesystem:
#      fstype: "{{ fs_type }}"
#      dev: "{{ block_device_openebs }}"
#  
#  - name: Mount filesystem
#    mount:
#      path: "{{ mount_point }}"
#      src: "{{ block_device_openebs }}"
#      fstype: "{{ fs_type }}"
#      state: mounted
  
