---
# NetApp Trident driver for ONTAP

- hosts: 'kube-master'
  vars:
    trident_installer: https://github.com/NetApp/trident/releases/download/v18.07.0/trident-installer-18.07.0.tar.gz

    namespace: trident
    deploy:    trident
  remote_user: solidfire
  run_once: true
  become: true

  tasks:

  #- name: Role Facts
  #  set_fact:
  #    block_device: '/dev/sdb'

  - name: Check for Trident Deployments
    shell: "kubectl get deployment {{ deploy }} -n {{ namespace }} --no-headers=1"
    register: check_trident_ds
    ignore_errors: true

  - debug: var=check_trident_ds.stdout_lines

  - name: Install apt package nfs-commoon
    package: 
      name:   nfs-common
      state:    present
    register: out

  - debug: var=out.stdout_lines

